steps:
  # Step 1: Build the Java application using Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/linear-theater-463712-r8/payment-backend'
      - '.'

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/linear-theater-463712-r8/payment-backend'

images:
  - 'gcr.io/linear-theater-463712-r8/payment-backend'

options:
  logging: CLOUD_LOGGING_ONLY
