steps:
  # Step 1: Build the Spring Boot app using Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
    id: 'Maven Build'

  # Step 2: Build the Docker image using the JAR just built
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/linear-theater-463712-r8/payment-backend'
      - '.'
    id: 'Docker Build'

  # Step 3: Push the image to GCR or Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/linear-theater-463712-r8/payment-backend'
    id: 'Push Image'

images:
  - 'gcr.io/linear-theater-463712-r8/payment-backend'
