apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-backend
  labels:
    app: payment-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-backend
  template:
    metadata:
      labels:
        app: payment-backend
    spec:
      containers:
        - name: payment-backend
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"